name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -t app:latest .  # Use app:latest for consistency

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Scan Image (Optional)
        uses: docker/build-push-action@v3
        with:
          push: false  # Set to true to push after successful build and scan
          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
          # Add these lines if using a vulnerability scanner:
          #   security-opts: |
          #     --fail-on-severe

      - name: Push image to GitHub Container Registry (Conditional)
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
        if: success() && steps.build-and-scan.outputs.success  # Only push on successful build and scan (if enabled)

      - name: Send Portainer webhook (Optional)
        run: |
          curl --insecure --connect-timeout 60 -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
