name: CI/CD
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: |
          ./gradlew clean bootBuildImage --imageName=app:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: blog
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Push image to GitHub Container Registry
        run: |
          docker tag blog
          docker push blog
