name: CI/CD
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Build Image
        run: |
          docker build -t blog/app:latest .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: blog_coldzy
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Push image to GitHub Container Registry
        run: |
          docker tag app:latest blog
          docker push blog

      - name: Send portainer webhook
        run: |
          curl --insecure --connect-timeout 60 -X POST ${{ secrets.PORTAINER_STACK_WEBHOOK }}
